<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Hitung Faktorial</name>
   <tag></tag>
   <elementGuidId>7902bffc-ca7e-41cf-a7d2-34aec7578a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hitung</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hitung']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>332a529d-06bf-405e-a014-916ecc71e65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block</value>
      <webElementGuid>4f934a9a-e231-46ce-9a68-70de10eba190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f2c24314-cf57-4c6b-a7f0-c1e6599f65bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hitung</value>
      <webElementGuid>cedbfae9-1a0c-4283-83d5-d035a89b0028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung
                                        Faktorial</value>
      <webElementGuid>c3382618-08f6-4983-b847-f0890a431fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung&quot;)</value>
      <webElementGuid>1878d872-0f78-4493-ab73-66c6f2768a43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hitung']</value>
      <webElementGuid>6cecce77-4cc0-473a-80a1-f65431a27bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Faktorial'])[1]/following::button[1]</value>
      <webElementGuid>659b3283-70dc-4109-87a3-c9ea48055f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laravel v8.72.0 (PHP v8.0.10)'])[1]/preceding::button[1]</value>
      <webElementGuid>e5148e5f-2aa6-4b69-b39a-2d38b5415748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6d7ea55b-d3f4-44a2-9b30-23b0106c275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'hitung' and (text() = 'Hitung
                                        Faktorial' or . = 'Hitung
                                        Faktorial')]</value>
      <webElementGuid>ae0fd91b-4aa4-44e6-b283-1ba75f472e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
