<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kalkulator Faktorial_input</name>
   <tag></tag>
   <elementGuidId>0d52f70e-2908-4bbc-8c26-c627295b9ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d6dc9d0-b882-4be8-b6d4-d676245d1009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ba42c0c-7f8f-413e-97a3-7615ea5c0e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9e0c0028-36af-4eb5-a538-5f1e956841bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>262c590b-66b8-4d0c-b829-8da3c13fbd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Angka</value>
      <webElementGuid>78690e52-1e0c-4427-a64f-440a1e81546e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83ec8a7f-f4bc-4c4d-8832-1d6c98c1e805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input&quot;)</value>
      <webElementGuid>d7af3837-13e7-4afd-b8ac-2f5169e3856b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input']</value>
      <webElementGuid>b5bd7dba-c102-4096-9003-885ff319901d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a629136-9a51-4729-b36a-37ebb52567fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input' and @placeholder = 'Masukkan Angka' and @name = 'input']</value>
      <webElementGuid>1f9e5612-031a-4e74-89e1-02fb136d1f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
